# Generated by Django 3.1 on 2020-09-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainHeading', models.CharField(blank=True, max_length=100, null=True)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('text1', models.CharField(blank=True, max_length=200, null=True)),
                ('Birthday', models.CharField(blank=True, max_length=100, null=True)),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.CharField(blank=True, max_length=100, null=True)),
                ('Degree', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Freelance', models.CharField(blank=True, max_length=100, null=True)),
                ('text2', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand_title', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio_Brands',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_address', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.CharField(blank=True, max_length=150, null=True)),
                ('c_phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('education_title', models.CharField(blank=True, max_length=100, null=True)),
                ('education_date', models.CharField(blank=True, max_length=100, null=True)),
                ('education_university', models.CharField(blank=True, max_length=100, null=True)),
                ('education_paragraph', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'My Education',
            },
        ),
        migrations.CreateModel(
            name='EexperienceMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_details', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lifting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('price_description', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'LIFTING EQUIPMENT',
                'verbose_name_plural': 'LIFTING EQUIPMENT',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio_photogallery',
            },
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('prints_title', models.CharField(blank=True, max_length=100, null=True)),
                ('prints_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('print_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio_Print',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('stext', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('valuenow', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('summary_title', models.CharField(blank=True, max_length=100, null=True)),
                ('summary_paragraph', models.CharField(blank=True, max_length=250, null=True)),
                ('summary_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'My Summary',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('web_title', models.CharField(blank=True, max_length=100, null=True)),
                ('web_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('web_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio_website',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_title', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_year', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_company', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.eexperiencemore')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'My Experience',
            },
        ),
    ]
