# Generated by Django 3.1 on 2020-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eexperiencemore',
            old_name='more_details',
            new_name='more_details1',
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eexperiencemore',
            name='more_details8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
