# Generated by Django 3.1 on 2020-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200903_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_company',
            field=models.CharField(blank=True, choices=[('Worked with clients Designed logos', 'Worked with clients Designed logos'), ('Develop Material & Mockups for the Web Page', 'Develop Material & Mockups for the Web Page')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_summary',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_summary',
            field=models.ManyToManyField(blank=True, null=True, to='website.EexperienceMore'),
        ),
    ]
