# Generated by Django 3.1 on 2020-09-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200903_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details2',
        ),
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details3',
        ),
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details4',
        ),
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details5',
        ),
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details6',
        ),
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details7',
        ),
        migrations.RemoveField(
            model_name='eexperiencemore',
            name='more_details8',
        ),
    ]
