# Generated by Django 3.1 on 2020-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200903_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Lifting',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_summary',
        ),
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(to='website.Tag'),
        ),
    ]
