# Generated by Django 3.1 on 2020-09-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200906_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='happycustomer',
            options={'verbose_name': 'HappyCustomer', 'verbose_name_plural': 'My Customer'},
        ),
        migrations.AlterModelOptions(
            name='intrest',
            options={'verbose_name': 'Intrest', 'verbose_name_plural': 'My Intrest'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'My Testimonial'},
        ),
        migrations.AddField(
            model_name='happycustomer',
            name='hometext',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialiconlink',
            name='yotube',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
