# Generated by Django 3.1 on 2020-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200906_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrest',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
