# Generated by Django 3.1 on 2020-09-07 07:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_intrest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFE600', max_length=100, null=True),
        ),
    ]
