# Generated by Django 3.1 on 2020-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_intrest_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='text2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_paragraph',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
