# Generated by Django 3.1 on 2020-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200907_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title_tag',
            field=models.CharField(default='Web developer | Kuwait', max_length=250),
        ),
    ]
