# Generated by Django 3.1 on 2020-09-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_aboutme_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialiconlink',
            name='behance',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
